name: Code Quality Check
permissions:
  contents: read
  pull-requests: write

# This workflow runs on every pull request targeting the main branch
on:
  pull_request:
    branches: [ main ]

jobs:
  ruff-check:
    name: Run Ruff Linter and Formatter
    runs-on: ubuntu-latest

    steps:
      # 1. Get the code from the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up the Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' # Choose your project's Python version

      # 3. Install Ruff
      - name: Install Ruff
        run: pip install ruff

      # 4. Run the Ruff linter
      #    This checks the code for errors and style violations.
      - name: Run Ruff Linter
        run: ruff check .

      # 5. Check code formatting with Ruff
      #    The --check flag makes Ruff fail if the code is NOT correctly formatted,
      #    without actually changing any files.
      - name: Check Ruff Formatting
        run: ruff format --check .